In [15]:
import pandas as pd
import numpy as np

from sklearn.utils import shuffle

In [16]:
flats = pd.read_csv('data_download/flats_cleaned.csv')
independent = pd.read_csv('data_download/house_cleaned.csv')

In [17]:
df_combined = pd.concat([flats, independent], ignore_index=True)

# Shuffle the rows
df_shuffled = shuffle(df_combined)

In [18]:
df_shuffled

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2476,2 BHK Flat in Sector 92 Gurgaon,flat,signature global city,0.780,7722.0,1010.0,Super Built up area 1010(93.83 sq.m.)Carpet ar...,2,2,3,others,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,NaN,Aug 2025,"['Iris Broadway Mall', 'Pataudi Road', 'Dwarka...",Under construction flat for sale in signature ...,"['1 Fan', '1 Light', '3 AC', '1 Modular Kitche...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
783,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.720,7850.0,2191.0,Super Built up area 2191(203.55 sq.m.),3,3,3+,servant room,"9th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",10.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Check out this 3 bhk apartment for sale in bpt...,"['5 Fan', '5 Light', '3 AC', 'No Bed', 'No Chi...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
606,3 BHK Flat in DLF Phase 3,flat,ambience lagoon,4.250,13281.0,3200.0,Super Built up area 3200(297.29 sq.m.)Carpet a...,3,4,3+,"servant room,pooja room","H Tower, DLF Phase 3, Gurgaon, Haryana",3.0,North-East,10+ Year Old,"['Micromax moulsari avenue metro station', 'In...",Looking for a 3 bhk property for sale in gurga...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
3233,12 Bedroom House for sale in Malibu Town,house,malibu towne,8.500,53125.0,1600.0,Built Up area: 1600 (148.64 sq.m.),12,12,3+,not available,"Redwood 14, Malibu Town, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",It's a wholly distinctive home with three open...,"['12 Wardrobe', '12 Fan', '1 Exhaust Fan', '10...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3523,5 Bedroom House for sale in New Colony,house,independent,0.890,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2891,2 BHK Flat in Sohna,flat,hcbs sports ville,0.269,4345.0,619.0,Built Up area: 619 (57.51 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",10.0,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Raw flat as given by builder. Good location ne...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management4 out of 5', 'Green Area4 out of 5..."
591,3 BHK Flat in Sector 67 Gurgaon,flat,ireo victory valley,3.650,13528.0,2698.0,Super Built up area 2698(250.65 sq.m.)Built Up...,3,4,3+,"pooja room,servant room","1805, Sector 67 Gurgaon, Gurgaon, Haryana",18.0,North,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",Ireo victory valley is one of gurgaon's most s...,"['6 Fan', '5 Light', '6 AC', '1 Chimney', '1 M...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of..."
3347,6 Bedroom House for sale in Laxmi Garden,house,independent,2.100,17284.0,1215.0,Plot area 135(112.88 sq.m.),6,6,3+,not available,"Near Tiokna Park, Laxmi Garden, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Rachna Dental Clinic',...",Triple story corner big house size 30 feet x 4...,"['3 Chimney', 'No AC', 'No Bed', 'No Curtains'...","['Water Storage', 'Visitor Parking', 'Waste Di...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2240,2 BHK Flat in Sector 37D Gurgaon,flat,ramprastha the edge towers,0.750,5319.0,1410.0,Built Up area: 1410 (130.99 sq.m.),2,2,3,not available,"Sector 37d, Delhi Gurgaon Expressway, Sector 3...",19.0,NaN,5 to 10 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...","2 bath, unfurnished, 19th floor (Of 19), rampr...",NaN,NaN,"['Green Area4 out of 5', 'Construction4 out of..."
3705,6 Bedroom House for sale in DLF Phase 1,house,independent,18.400,1859.0,98978.0,Plot area 502(419.74 sq.m.)Carpet area: 11000 ...,6,8,3+,"pooja room,store room,servant room","111, DLF Phase 1, Gurgaon, Haryana",4.0,South,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Dlf city phase 1 a block duplex kothi sale in ...,"['6 Wardrobe', '16 Fan', '1 Exhaust Fan', '8 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [19]:
df_shuffled.reset_index(drop=True, inplace=True)

In [20]:
df_shuffled.shape

(3960, 20)

In [21]:
df_shuffled.columns

Index(['property_name', 'property_type', 'society', 'price', 'price_per_sqft',
       'area', 'areaWithType', 'bedRoom', 'bathroom', 'balcony',
       'additionalRoom', 'address', 'floorNum', 'facing', 'agePossession',
       'nearbyLocations', 'description', 'furnishDetails', 'features',
       'rating'],
      dtype='object')